"""Export an arena's PUBLIC split as an Inspect AI task module.

WHY INSPECT SPECIFICALLY
-----------------------
Inspect AI (UK AI Security Institute) is the format the public benchmarking hubs
actually ingest: OpenBench is built on it, and Epoch AI's benchmarking hub stores
per-question logs in Inspect's viewer. A benchmark that publishes only a bespoke
JSON API is invisible to that ecosystem no matter how good it is — which is how a
model card ends up citing five benchmarks and not this one.

WHAT THIS IS, AND WHAT IT IS NOT
--------------------------------
An EXPORT, not a migration. Task generation, gold, scoring and contamination
control stay here; the emitted module is a thin harness adapter. Exactly as with
`export_kaggle`, scoring is DELEGATED to the arena's own scorer. If the exported
copy re-implemented scoring, a score reported by OpenBench under this arena's
name would silently mean something different from a score on
metasciencearena.app — the same name attached to two different measurements is
worse than no export at all.

CONTAMINATION
-------------
Only `visibility: "public"` envelopes are exported, filtered through
`framework.holdout.is_held_out`, which treats a MISSING marker as held-out.
Export is publication: an unmarked task is never assumed safe. The exporter
refuses to write a zero-task file, because at the shell an empty export is
indistinguishable from a successful one.
"""
from __future__ import annotations

import argparse
import inspect
import json
import sys
from pathlib import Path

from framework.discovery import load_arena
from framework.holdout import is_held_out
from framework.paths import arenas_root
from framework.runner import _import_arena_module

_TEMPLATE = '''"""Inspect AI task for the `{arena_id}` arena of Meta Science Arena.

GENERATED by `python -m framework export-inspect` — do not edit by hand.

Arena:      {arena_id}
Task set:   {task_set}  (public split only — held-out tasks are never exported)
Tasks:      {n_tasks}
Source:     https://metasciencearena.app/arenas/{arena_id}
Cite:       see CITATION.cff in the metasciencearena package.

Run it:

    pip install "metasciencearena[inspect]"
    git clone https://github.com/giladfeldman/metasciencearena   # the arenas themselves
    export SCIENCEARENA_ARENAS_ROOT=metasciencearena/arenas
    inspect eval {module_name}.py --model <provider>/<model>

The clone is REQUIRED: the wheel ships the scoring machinery, not the arena data,
so this module raises RootNotFoundError without it.

Scoring delegates to the arena's own scorer and validates against the arena's own
output schema, and unparseable or schema-invalid output is raised as a sample
error rather than scored 0.0 — because the leaderboard EXCLUDES such a task from
its mean, and Inspect's accuracy() averages every sample it is given. Those two
choices are what make a number here mean what the published number means. This
module does not re-implement scoring.
"""
import json
from pathlib import Path

from inspect_ai import Task, task
from inspect_ai.dataset import Sample
from inspect_ai.scorer import Score, Target, accuracy, scorer, stderr
from inspect_ai.solver import generate
from jsonschema import Draft202012Validator

from framework.discovery import load_arena
from framework.paths import arenas_root
from framework.runner import _import_arena_module

ARENA_ID = {arena_id!r}
TASK_SET = {task_set!r}
_TASKS = json.loads(Path(__file__).with_suffix(".tasks.json").read_text(encoding="utf-8"))

_ARENA_DIR = arenas_root() / ARENA_ID
_SCORER = _import_arena_module(_ARENA_DIR, "scorer")
#: The SAME output schema the runner validates against (runner.py:205). Without
#: it, schema-invalid-but-parseable JSON that the leaderboard treats as an error
#: would earn partial credit here.
_VALIDATOR = Draft202012Validator(
    json.loads(load_arena(_ARENA_DIR)["output_schema_path"].read_text(encoding="utf-8"))
)


class ArenaOutputRejected(ValueError):
    """Output the leaderboard would record as errored, and EXCLUDE from the mean."""


@scorer(metrics=[accuracy(), stderr()])
def arena_scorer():
    """Delegate to the arena's own scorer — never re-implement it here.

    On unparseable or schema-invalid output this RAISES rather than scoring 0.0.
    That is not a stylistic choice: the runner records such a task with
    `breakdown.error` (runner.py:648-656) and both report engines then EXCLUDE it
    from the mean (`_is_scored`). Inspect's `accuracy()` is a mean over every
    sample it is given, so returning 0.0 here would publish a systematically
    lower number under the same arena name — measured: 27 answers at 0.9 plus 3
    malformed reads 0.90 on the leaderboard and 0.81 under `accuracy()`. Raising
    makes Inspect record a sample error, which its metrics exclude, matching the
    leaderboard. (Fable 5 cross-review, 2026-08-15.)
    """

    async def score(state, target: Target) -> Score:
        task_id = state.metadata["task_id"]
        raw = state.output.completion
        try:
            output = json.loads(raw)
        except json.JSONDecodeError as exc:
            raise ArenaOutputRejected(f"output was not valid JSON: {{exc}}") from exc
        errors = sorted(_VALIDATOR.iter_errors(output), key=lambda e: e.path)
        if errors:
            raise ArenaOutputRejected(
                "output_schema_violation: " + "; ".join(e.message for e in errors)
            )
        result = _SCORER.score(output, _TASKS[task_id]["ground_truth"])
        return Score(value=float(result["primary"]), answer=raw,
                     explanation=json.dumps(result.get("breakdown", {{}}), ensure_ascii=False))

    return score


@task
def {func_name}() -> Task:
    samples = [
        Sample(input=t["prompt"], target=task_id, metadata={{"task_id": task_id}})
        for task_id, t in sorted(_TASKS.items())
    ]
    return Task(dataset=samples, solver=generate(), scorer=arena_scorer())
'''


def _safe_ident(arena_id: str) -> str:
    cleaned = "".join(c if c.isalnum() else "_" for c in arena_id).strip("_")
    return cleaned or "arena_task"


def export_arena(
    arena_id: str,
    task_set: str,
    out_dir: Path,
    *,
    prompt_template: Path | None = None,
) -> int:
    """Write ``<out_dir>/<arena_id>.py`` + ``.tasks.json``. Returns the task count."""
    arena_dir = arenas_root() / arena_id
    arena = load_arena(arena_dir)
    generator = _import_arena_module(arena_dir, "generator")

    manifest = arena["manifest"]
    splits = manifest.get("benchmark_splits") or {}
    seed = ((splits.get("revealed") or {}).get("seed")) or 0

    template = prompt_template.read_text(encoding="utf-8") if prompt_template else "{{INPUT_TEXT}}"

    tasks: dict[str, dict] = {}
    gen_kwargs = {}
    if "split" in inspect.signature(generator.generate).parameters:
        gen_kwargs["split"] = "revealed"
    for envelope in generator.generate(task_set, seed, **gen_kwargs):
        # Fail-safe: `is_held_out` returns True for an UNMARKED envelope.
        if is_held_out(envelope):
            continue
        payload = envelope["input"]
        text = (
            payload["text"]
            if isinstance(payload, dict) and "text" in payload
            else json.dumps(payload, ensure_ascii=False)
        )
        tasks[envelope["task_id"]] = {
            "envelope": envelope,
            "ground_truth": generator.ground_truth(envelope["task_id"]),
            "prompt": template.replace("{{INPUT_TEXT}}", text),
        }

    if not tasks:
        raise SystemExit(
            f"REFUSING to write an empty export for {arena_id}: the generator emitted no "
            f"PUBLIC tasks. Either the arena is held-out-only or the visibility marker is "
            f"missing (which is read as held-out, by design). An empty task file would look "
            f"exactly like a successful export."
        )

    out_dir.mkdir(parents=True, exist_ok=True)
    module_name = arena_id.replace("-", "_")
    module_path = out_dir / f"{module_name}.py"
    tasks_path = module_path.with_suffix(".tasks.json")

    module_path.write_text(
        _TEMPLATE.format(
            arena_id=arena_id,
            task_set=task_set,
            n_tasks=len(tasks),
            module_name=module_name,
            func_name=_safe_ident(module_name),
        ),
        encoding="utf-8",
    )
    tasks_path.write_text(json.dumps(tasks, indent=2, ensure_ascii=False), encoding="utf-8")
    return len(tasks)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="framework export-inspect", description=__doc__)
    ap.add_argument("--arena", required=True)
    ap.add_argument("--task-set", default="v1")
    ap.add_argument("--out", type=Path, default=Path("build/inspect"))
    ap.add_argument("--prompt", type=Path, default=None,
                    help="Prompt template with {{INPUT_TEXT}}; defaults to the raw input.")
    args = ap.parse_args(argv)
    n = export_arena(args.arena, args.task_set, args.out, prompt_template=args.prompt)
    print(f"exported {n} public task(s) for {args.arena} to {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
