"""Export an arena's PUBLIC split as a Kaggle Benchmarks task module.

WHAT THIS IS, AND WHAT IT IS NOT
--------------------------------
Kaggle's `kbench` SDK is an *execution harness*: it runs a model over a set of
tasks and collects verdicts. This framework already owns task generation, gold,
scoring and contamination control. So this is an EXPORT, not a migration —
nothing about how a score is computed moves to Kaggle, and the numbers on
metasciencearena.app keep coming from `framework.scoring`.

The emitted module declares one `@kbench.task` per public task and scores it by
calling this package's own scorer. That is the only honest arrangement: if the
Kaggle copy re-implemented scoring, a "score" there would silently mean
something different from a score here, under the same arena name.

CONTAMINATION
-------------
Only `visibility: "public"` envelopes are exported, and the check is
`framework.holdout.is_held_out`, which treats a MISSING visibility marker as
held-out. Exporting is publication: an unmarked task must never be assumed safe.

The exporter refuses to write a file containing zero tasks, because an empty
export is indistinguishable from a successful one at the shell.
"""
from __future__ import annotations

import argparse
import inspect
import json
import sys
from pathlib import Path

from framework.discovery import load_arena
from framework.holdout import is_held_out
from framework.paths import arenas_root
from framework.runner import _import_arena_module

_TEMPLATE = '''"""Kaggle Benchmarks tasks for the `{arena_id}` arena.

GENERATED by `python -m framework export-kaggle` — do not edit by hand.

Arena:      {arena_id}
Task set:   {task_set}  (split: revealed / public only)
Tasks:      {n_tasks}
Source:     https://metasciencearena.app/arenas/{arena_id}
Cite:       see CITATION.cff in the metasciencearena package.

Scoring calls `metasciencearena`'s own scorer, so a verdict here means exactly
what the published leaderboard means. Install it first:

    pip install metasciencearena
"""
import json
from pathlib import Path

import kbench

from framework.paths import arenas_root
from framework.runner import _import_arena_module

ARENA_ID = {arena_id!r}
TASK_SET = {task_set!r}
_TASKS = json.loads(Path(__file__).with_suffix(".tasks.json").read_text(encoding="utf-8"))


_SCORER = _import_arena_module(arenas_root() / ARENA_ID, "scorer")


def _score(task_id: str, output: dict) -> float:
    """Delegate to the arena's own scorer — never re-implement it here."""
    result = _SCORER.score(output, _TASKS[task_id]["ground_truth"])
    return float(result["primary"])


{task_defs}
'''

_TASK_DEF = '''
@kbench.task(name={name!r})
def {func}(model):
    """{prompt_hint}"""
    task = _TASKS[{task_id!r}]
    reply = model.generate(task["prompt"])
    try:
        output = json.loads(reply)
    except json.JSONDecodeError:
        return 0.0  # an unparseable answer is a wrong answer, not an error
    return _score({task_id!r}, output)
'''


def _safe_ident(task_id: str, index: int) -> str:
    cleaned = "".join(c if c.isalnum() else "_" for c in task_id).strip("_")
    return f"task_{index:03d}_{cleaned}"[:60]


def export_arena(arena_id: str, task_set: str, out_dir: Path, *, prompt_template: Path | None = None) -> int:
    """Write ``<out_dir>/<arena_id>.py`` + ``.tasks.json``. Returns the task count."""
    arena_dir = arenas_root() / arena_id
    arena = load_arena(arena_dir)
    generator = _import_arena_module(arena_dir, "generator")

    manifest = arena["manifest"]
    splits = manifest.get("benchmark_splits") or {}
    seed = ((splits.get("revealed") or {}).get("seed")) or 0

    template = prompt_template.read_text(encoding="utf-8") if prompt_template else "{{INPUT_TEXT}}"

    tasks: dict[str, dict] = {}
    # `--split revealed` implies public-only elsewhere in the framework; here the
    # visibility filter below is the authority, because export IS publication.
    gen_kwargs = {}
    if "split" in inspect.signature(generator.generate).parameters:
        gen_kwargs["split"] = "revealed"
    for envelope in generator.generate(task_set, seed, **gen_kwargs):
        # Fail-safe: `is_held_out` returns True for an UNMARKED envelope.
        if is_held_out(envelope):
            continue
        payload = envelope["input"]
        text = payload["text"] if isinstance(payload, dict) and "text" in payload else json.dumps(
            payload, ensure_ascii=False
        )
        tasks[envelope["task_id"]] = {
            "envelope": envelope,
            "ground_truth": generator.ground_truth(envelope["task_id"]),
            "prompt": template.replace("{{INPUT_TEXT}}", text),
        }

    if not tasks:
        raise SystemExit(
            f"REFUSING to write an empty export for {arena_id}: the generator emitted no "
            f"PUBLIC tasks. Either the arena is held-out-only or the visibility marker is "
            f"missing (which is read as held-out, by design). An empty task file would look "
            f"exactly like a successful export."
        )

    out_dir.mkdir(parents=True, exist_ok=True)
    module_path = out_dir / f"{arena_id.replace('-', '_')}.py"
    tasks_path = module_path.with_suffix(".tasks.json")

    defs = "".join(
        _TASK_DEF.format(
            name=f"{arena_id}/{task_id}",
            func=_safe_ident(task_id, i),
            task_id=task_id,
            prompt_hint=f"{arena_id} task {task_id}",
        )
        for i, task_id in enumerate(sorted(tasks))
    )
    module_path.write_text(
        _TEMPLATE.format(
            arena_id=arena_id, task_set=task_set, n_tasks=len(tasks), task_defs=defs
        ),
        encoding="utf-8",
    )
    tasks_path.write_text(json.dumps(tasks, indent=2, ensure_ascii=False), encoding="utf-8")
    return len(tasks)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="framework export-kaggle", description=__doc__)
    ap.add_argument("--arena", required=True)
    ap.add_argument("--task-set", default="v1")
    ap.add_argument("--out", type=Path, default=Path("build/kaggle"))
    ap.add_argument("--prompt", type=Path, default=None,
                    help="Prompt template with {{INPUT_TEXT}}; defaults to the raw input.")
    args = ap.parse_args(argv)
    n = export_arena(args.arena, args.task_set, args.out, prompt_template=args.prompt)
    print(f"exported {n} public task(s) for {args.arena} to {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
